# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(805, 339)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(100, 70, 481, 161))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.write_line = QtWidgets.QLineEdit(self.widget)
        self.write_line.setObjectName("write_line")
        self.gridLayout.addWidget(self.write_line, 2, 2, 1, 1)
        self.read_line = QtWidgets.QLineEdit(self.widget)
        self.read_line.setObjectName("read_line")
        self.gridLayout.addWidget(self.read_line, 1, 2, 1, 1)
        self.read_one_data = QtWidgets.QPushButton(self.widget)
        self.read_one_data.setObjectName("read_one_data")
        self.gridLayout.addWidget(self.read_one_data, 1, 1, 1, 1)
        self.write_one_data = QtWidgets.QPushButton(self.widget)
        self.write_one_data.setObjectName("write_one_data")
        self.gridLayout.addWidget(self.write_one_data, 2, 1, 1, 1)
        self.all_write = QtWidgets.QPushButton(self.widget)
        self.all_write.setObjectName("all_write")
        self.gridLayout.addWidget(self.all_write, 0, 0, 1, 2)
        self.read_addr = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_addr.sizePolicy().hasHeightForWidth())
        self.read_addr.setSizePolicy(sizePolicy)
        self.read_addr.setObjectName("read_addr")
        self.gridLayout.addWidget(self.read_addr, 1, 0, 1, 1)
        self.write_addr = QtWidgets.QLineEdit(self.widget)
        self.write_addr.setObjectName("write_addr")
        self.gridLayout.addWidget(self.write_addr, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.read_one_data.setText(_translate("Form", "读取数据"))
        self.write_one_data.setText(_translate("Form", "写入数据"))
        self.all_write.setText(_translate("Form", "批量写入数据"))
